const reportData = [
  {
    id: 1,
    title: 'Traffic Police asks me some money',
    type: 'Red-flag',
    createdOn: '20-Apr-2019',
    createdBy: 4,
    comment: 'One traffic police who has rank of Caporal asks me some money while I was stopping my car to let students cross te road to school and he threaten me to charge me 50000FRW of disobedience',
    location: '10845635353 173645473999',
    status: 'under investigation',
    images: [],
    videos: [],
    tag: 'corruption',
  },
  {
    id: 2,
    title: 'ANTI-CORRUPTION CLUB',
    type: 'Red-flag',
    createdOn: '20-Apr-2019',
    createdBy: 4,
    comment: 'One traffic police who has rank of Caporal asks me some money while I was stopping my car to let students cross te road to school and he threaten me to charge me 50000FRW of disobedience',
    location: '10845635353 173645473999',
    status: 'pending',
    images: [],
    videos: [],
    tag: 'corruption',
  },
  {
    id: 3,
    title: 'ANTI-CORRUPTION CLUB',
    type: 'Red-flag',
    createdOn: '20-Apr-2019',
    createdBy: 1,
    comment: 'One traffic police who has rank of Caporal asks me some money while I was stopping my car to let students cross te road to school and he threaten me to charge me 50000FRW of disobedience',
    location: '10845635353 173645473999',
    status: 'rejected',
    images: [],
    videos: [],
    tag: 'corruption',
  },
  {
    id: 4,
    title: 'TO avoid excess consumption of Alcohol',
    type: 'intervention',
    createdOn: '23-Aug-2019',
    createdBy: 4,
    comment: 'I am writing this because of many young people are poisoned theirselves in alcohol and smoking drugs',
    location: '',
    status: 'resolved',
    images: [],
    videos: [],
    tag: 'Alcohol',
  },

];

export default reportData;
