const users = [
  {
    id: 1,
    firstname: 'NIYODUSENGA',
    lastname: 'Clement',
    email: 'niyodusenga.clement@yahoo.com',
    phoneNumber: '250780282575',
    username: 'NIYODUSENGA',
    password: '$2b$10$yXNUhBF/wyZ8Mc7vLeD9tujw8fqjASJVh0gKG0vcaNJZg7RAg3KPS',
    isAdmin: false,
  },
  {
    id: 2,
    firstname: 'Admin',
    lastname: 'Administrator',
    email: 'admin@gmail.com',
    phoneNumber: '250780282575',
    username: 'Admin',
    password: '$2b$10$RBX51IJbmDslGdSu//2HAuNpq5usjoO74ktxL9PNYpJYIM.VwmmZe',
    isAdmin: false,
  },
  {
    id: 3,
    firstname: 'IRADUKUNDA',
    lastname: 'Fidele',
    email: 'iradukunda@yahoo.com',
    phoneNumber: '250780282570',
    username: 'FIDELE',
    password: '$2b$10$rlyI9hTZkBi9CVetQPQBa.hS9AEwwrQv8nEqNwQYxXcVC3oom/ncu',
    isAdmin: false,
  },
  {
    id: 4,
    firstname: 'MUGENZI',
    lastname: 'Oscar',
    email: 'oscarmugenzi@gmail.com',
    phoneNumber: '250780282575',
    username: 'MUGENZI',
    password: '$2b$10$A6PTLLNzgsyEDZRBc.eMs.CrBqx6gzwSpEbwDz1mRdE.qHmoZZKS6',
    isAdmin: false,
  },
  {
    id: 5,
    firstname: 'MISTICO',
    lastname: 'Clement',
    email: 'clementmistico@gmail.com',
    phoneNumber: '250780282575',
    username: 'Mistico',
    password: '$2b$10$cVjjDBFR8BY1EtM3avYy0eQEdHuUlm8O2fulYVx9PFDcdYqdr19Be',
    isAdmin: true,
  },
];
export default users;
